name: "Gollum"
description: "Git based wiki"
version: "0.1.0"
image: ghcr.io/wozz/ha-addons/gollum-{arch}
panel_icon: mdi:file-document-multiple-outline
slug: "gollum"
hassio_api: true
init: false
ingress: true
arch:
  - aarch64
options: {}
schema: {}
