name: "Gollum"
description: "Git based wiki"
version: "0.0.3"
image: ghcr.io/wozz/ha-addons/gollum-{arch}
slug: "gollum"
init: false
startup: application
ingress: true
ingress_port: 4567
arch:
  - aarch64
options: {}
schema: {}
