name: "Gollum"
description: "Git based wiki"
version: "0.0.10"
image: ghcr.io/wozz/ha-addons/gollum-{arch}
slug: "gollum"
hassio_api: true
init: false
startup: application
ingress: true
arch:
  - aarch64
options: {}
schema: {}
