name: "JuicePassProxy"
description: "This tool will publish JuiceBox data by using a Man in the Middle UDP proxy to MQTT that is auto-discoverable by HomeAssistant."
version: "0.0.3"
image: ghcr.io/wozz/ha-addons/juicepassproxy-{arch}
slug: "juicepassproxy"
ports:
  "8047/udp": 8047
arch:
  - aarch64
discovery:
  - mqtt
services:
  - "mqtt:need"
options:
  juicebox_host: null
  ha_host: null
  juicebox_device_name: JuiceBox
schema:
  juicebox_host: str
  ha_host: str
  juicebox_device_name: str
