name: "JuicePassProxy"
description: "This tool will publish JuiceBox data by using a Man in the Middle UDP proxy to MQTT that is auto-discoverable by HomeAssistant."
version: "0.0.4"
image: ghcr.io/wozz/ha-addons/juicepassproxy-{arch}
slug: "juicepassproxy"
ports:
  "8047/udp": 8047
  "8042/udp": 8042
arch:
  - aarch64
discovery:
  - mqtt
services:
  - "mqtt:need"
options:
  juicebox_host: null
  juicebox_device_name: JuiceBox
  dst: 158.47.1.128:8042
schema:
  juicebox_host: str
  juicebox_device_name: str
  dst: str
