name: Matter Server UI
version: "0.2.2"
image: "ghcr.io/wozz/ha-addons/matter-server-ui-{arch}"
slug: matter-server-ui
description: "Web UI to connect directly to the home assistant matter server"
url: "https://github.com/wozz/ha-addons/tree/main/matter-server-ui"
arch:
  - aarch64
advanced: true
ingress: true
ingress_port: 80
panel_icon: mdi:router-network-wireless
panel_title: Matter UI
stage: experimental
